### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by vanja-san** [EzioTheDeadPoet/MO2Witcher3SupportPlugin#1]
Is it possible to make an installation specifying 3 folders (I used a little Photoshop):

<details>
  <summary>Picture</summary>

![1](https://user-images.githubusercontent.com/7201687/94984789-38154880-057a-11eb-829b-5d59e0a8fd3b.png)

</details>

_And please tell me how to install mods. Tried moving them to <mods> but when enabled the mod is not installed in the game folder._

**Comment by EzioTheDeadPoet** [comment]
that's sadly a limitation based on how Mod Organizer works. also this is highly WIP and gets inconsistent with it's functionality someone who had a very big setup wanted to get it to work but sometimes the game wouldn't load some of the mods. so it is best to just make a manual Witcher 3 setup or to try using Vortex, tho regarding Vortex I can't give any tips since I never used it.

**Comment by vanja-san** [comment]
> 
> 
> that's sadly a limitation based on how Mod Organizer works. also this is highly WIP and gets inconsistent with it's functionality someone who had a very big setup wanted to get it to work but sometimes the game wouldn't load some of the mods. so it is best to just make a manual Witcher 3 setup or to try using Vortex, tho regarding Vortex I can't give any tips since I never used it.

I wouldn't try this plugin if I liked Vortex!
All that bad? It always seemed to me that unpacking and moving through folders is not such a problem for any program!
_Sorry for my English!_

**Comment by EzioTheDeadPoet** [comment]
MO uses a virtual file system that overlaps itself over your actual installation and forces it to run with all those files there, but because of how that process works you, a) can't make it so it uses the folder where the .exe file of the game is, so I had to choose either `mods` or `dlc` and b) for some me and basically everyone unknown reason it doesn't detect all installed mods/ can't load all of them with the vfs sometimes.

**Comment by vanja-san** [comment]
Damn, how complicated everything is. 😔
I understood! I'm going to continue to poke around in an inconvenient mod manager!
